# Generated by Django 6.1.1 on 2026-10-08 06:03

import django.db.models.deletion
import documents.models
import documents.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, verbose_name='Nội dung'),
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, storage=documents.storage.PrivateDocumentStorage(), upload_to=documents.models.document_file_upload_to, verbose_name='Tệp lưu trữ')),
                ('display_name', models.CharField(max_length=255, verbose_name='Tên hiển thị')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('png', 'PNG'), ('jpg', 'JPG'), ('jpeg', 'JPEG')], max_length=4, verbose_name='Loại tệp')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='Dung lượng (byte)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='documents.document', verbose_name='Tài liệu')),
            ],
            options={
                'verbose_name': 'tệp đính kèm',
                'verbose_name_plural': 'tệp đính kèm',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Tên thư mục')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_folders', to='accounts.department', verbose_name='Phòng ban')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_folders', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sở hữu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='documents.documentfolder', verbose_name='Thư mục cha')),
            ],
            options={
                'verbose_name': 'thư mục tài liệu',
                'verbose_name_plural': 'thư mục tài liệu',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder', verbose_name='Thư mục'),
        ),
    ]
