# Generated by Django 6.1.1 on 2026-10-04 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Tên thao tác')),
                ('object_type', models.CharField(max_length=100, verbose_name='Loại đối tượng')),
                ('object_id', models.CharField(max_length=255, verbose_name='Mã đối tượng')),
                ('result', models.CharField(max_length=50, verbose_name='Kết quả')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Thông tin chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'nhật ký kiểm toán',
                'verbose_name_plural': 'nhật ký kiểm toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
