# Generated by Django 6.1.1 on 2026-10-04 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Xem'), ('edit', 'Chỉnh sửa')], max_length=10, verbose_name='Loại quyền')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời hạn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm thu hồi')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document', verbose_name='Tài liệu')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_document_shares', to=settings.AUTH_USER_MODEL, verbose_name='Người cấp quyền')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_document_shares', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'lượt chia sẻ tài liệu',
                'verbose_name_plural': 'lượt chia sẻ tài liệu',
                'ordering': ['-created_at'],
            },
        ),
    ]
